// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapter/storage/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/adapter/storage/interfaces.go -destination=internal/mocks/storage_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockImageStorage is a mock of ImageStorage interface.
type MockImageStorage struct {
	ctrl     *gomock.Controller
	recorder *MockImageStorageMockRecorder
	isgomock struct{}
}

// MockImageStorageMockRecorder is the mock recorder for MockImageStorage.
type MockImageStorageMockRecorder struct {
	mock *MockImageStorage
}

// NewMockImageStorage creates a new mock instance.
func NewMockImageStorage(ctrl *gomock.Controller) *MockImageStorage {
	mock := &MockImageStorage{ctrl: ctrl}
	mock.recorder = &MockImageStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageStorage) EXPECT() *MockImageStorageMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockImageStorage) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockImageStorageMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockImageStorage)(nil).Delete), ctx, key)
}

// GetSignedURL mocks base method.
func (m *MockImageStorage) GetSignedURL(key string, expiry time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSignedURL", key, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSignedURL indicates an expected call of GetSignedURL.
func (mr *MockImageStorageMockRecorder) GetSignedURL(key, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSignedURL", reflect.TypeOf((*MockImageStorage)(nil).GetSignedURL), key, expiry)
}

// GetURL mocks base method.
func (m *MockImageStorage) GetURL(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURL", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetURL indicates an expected call of GetURL.
func (mr *MockImageStorageMockRecorder) GetURL(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURL", reflect.TypeOf((*MockImageStorage)(nil).GetURL), key)
}

// Upload mocks base method.
func (m *MockImageStorage) Upload(ctx context.Context, key string, reader io.Reader, contentType string, size int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, key, reader, contentType, size)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockImageStorageMockRecorder) Upload(ctx, key, reader, contentType, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockImageStorage)(nil).Upload), ctx, key, reader, contentType, size)
}

// MockImageProcessor is a mock of ImageProcessor interface.
type MockImageProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockImageProcessorMockRecorder
	isgomock struct{}
}

// MockImageProcessorMockRecorder is the mock recorder for MockImageProcessor.
type MockImageProcessorMockRecorder struct {
	mock *MockImageProcessor
}

// NewMockImageProcessor creates a new mock instance.
func NewMockImageProcessor(ctrl *gomock.Controller) *MockImageProcessor {
	mock := &MockImageProcessor{ctrl: ctrl}
	mock.recorder = &MockImageProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProcessor) EXPECT() *MockImageProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockImageProcessor) Process(reader io.Reader, mimeType string) (io.Reader, int64, int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", reader, mimeType)
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(int)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// Process indicates an expected call of Process.
func (mr *MockImageProcessorMockRecorder) Process(reader, mimeType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockImageProcessor)(nil).Process), reader, mimeType)
}
